agriturf_supplies/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'agriturf_supplies.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'content.views.home', name='home'),
    (r'^content/', include('content.urls', app_name='content', namespace="content")),
    (r'^services/', include('services.urls', app_name='services', namespace="services")),
    (r'^shop/', include('shop.urls', app_name='shop', namespace="shop")),
    (r'^newsletter/', include('newsletter.urls', app_name='newsletter', namespace="newsletter")),

)

# don't run static files in production!!
if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
            url(r'^static/(?P<path>.*)$', 'serve'),
        )

    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
    )

# Configuration for admin Title:
admin.site.site_header = 'Agriturf Administration'

services/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('agriturf_supplies.services.views',

    #(r'^index/$', views.home), # main urls.py maps this directly to /
    url(r'^schedule/$', views.schedule, name='schedule'),
    url(r'^browse/$', views.search, name='search'),
    url(r'^browse/(\d+)$', views.search, name='filter'),
    url(r'^solution/(?P<slug>.*)$', views.view, name='view'),

)

shop/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('agriturf_supplies.services.views',

    #(r'^index/$', views.home), # main urls.py maps this directly to /
    url(r'^product/(?P<slug>.*)$', views.product, name='view_product'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^checkout/$', views.checkout, name='start_checkout'),
    url(r'^checkout/(\d+)$', views.checkout, name='checkout_step'),

)

services/models.py
import itertools

from django.db import models
from django.utils.text import slugify


class Service(models.Model):

    name = models.CharField(max_length=500)
    slug = models.CharField(max_length=500)
    description = models.TextField()
    identification_guide = models.TextField()
    image_1 = models.FileField(upload_to='services/images/')
    image_2 = models.FileField(upload_to='services/images/', blank=True)
    image_3 = models.FileField(upload_to='services/images/', blank=True)
    image_4 = models.FileField(upload_to='services/images/', blank=True)
    image_5 = models.FileField(upload_to='services/images/', blank=True)
    is_featured_solution = models.BooleanField(default=False)
    featured_solution_weight = models.IntegerField(default=5)
    category = models.ForeignKey('Category')
    related_products = models.ManyToManyField('shop.Product', blank=True, null=True)
    related_services = models.ManyToManyField('self', blank=True, null=True)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        """
        Creating unique slug on save by adding an integer if it
        already exists.
        """

        self.slug = original = slugify(self.name)
        for x in itertools.count(2):
            if not Service.objects.filter(slug=self.slug).exists():
                break
            self.slug = '%s-%d' % (original, x)
        super(Service, self).save(*args, **kwargs)


class Category(models.Model):

    name = models.CharField(max_length=255)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='subcategories')

    def is_child(self):
        if self.parent:
            return True
        else:
            return False

    def is_parent(self):
        return not self.is_child()

    def __unicode__(self):
        if self.parent:
            return "%s -> %s" % (self.parent.name, self.name)
        else:
            return "%s" % (self.name)

    def get_category_ids(self):
        """
        returns a list of ids for the parent id and all child ids if parent
        """
        if self.is_parent():
            cats = Category.objects.filter(parent_id=self.id)
            return [c.id for c in cats]

        else:
            return [self.id]


    @classmethod
    def get_menu(cls, current_id=0):
        """
        returns a hierarchical menu. type: list of dictionaries.
        Param: current_id - which used to determine active menu
        """

        if not current_id:
            current_id = 1


        menu_items = cls.objects.order_by('id')
        parents = [item for item in menu_items if item.is_parent()]
        children = [item for item in menu_items if item.is_child()]
        # create menu parent child relationship
        # menu = [  {'parent':parent1, 'children':[child1, child2...] },
        #           {'parent':parent2, 'children':[child3, child4...] }  ]
        active = False
        menu = []
        for p in parents:
            children_of_parent = [c for c in children if c.parent_id == p.id]
            if current_id:
                active = cls.is_menu_active(current_id, children_of_parent, p)
            menu.append({'parent':p, 'children':children_of_parent, 'active':active})
        return menu

    @classmethod
    def is_menu_active(cls,active_id, child_items, parent):
        """

        """
        active = False
        for category in child_items + [parent]:
            if int(active_id) == category.id:
                return True
        return False

    class Meta:
        verbose_name_plural = "categories"
        ordering = ['-parent_id', '-id']

services/forms.py
from django.forms import ModelForm

from shop.models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['name', 'email', 'phone', 'address1', 'zip_code']

services/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseBadRequest
from django.template import Template
from django.shortcuts import render
from models import Category, Service
from forms import OrderForm
from django.db.models import Q
from django.core.paginator import EmptyPage, Paginator, PageNotAnInteger

# Create your views here.


def view(request, slug):
    success = False
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            success = True
        else:
            return HttpResponseBadRequest("A error ocurred while processing your request - %s" % form.errors)
    service = Service.objects.get(slug=slug)
    return render(request, 'services/view.html', {"service": service, 'success': success})


def schedule(request):
    return render(request, 'services/schedule.html', {})


def search(request, category=None):
    if category:
        category = Category.objects.get(pk=category)
        selected = category
    else:
        category = Category.objects.get(pk=1)
        selected = None

    cat_ids = category.get_category_ids()
    print cat_ids
    services = Service.objects.filter(category_id__in=cat_ids)
    paginator = Paginator(services, 9)

    page = request.GET.get('page')
    try:
        services = paginator.page(page)
    except PageNotAnInteger:
        services = paginator.page(1)
    except EmptyPage:
        services = paginator.page(paginator.num_pages)

    menu = Category.get_menu(category.id)

    return render(request, 'services/search.html', {'page': 'solutions', 'menu': menu, 'services': services, 'selected': selected})

templates/services/_accordian_menu.html
       <!-- Left Accordian -->
        <div class="col-lg-3 col-sm-4" style="margin-top:30px; margin-bottom:75px">
            <h4 style="margin-bottom:25px">Problem Identifier</h4>

            <div class="panel-group" id="accordion">
                
                {% for menu_item in menu%}
                <div class="panel panel-default">

                    <!-- Parent Category-->
                    <div class="panel-heading">
                        <a data-toggle="collapse" data-parent="#accordion" href="#{{ forloop.counter }}" class="fora">
                            <h4 class="panel-title somestyle">
                                {{ menu_item.parent.name }}
                            </h4>
                        </a>
                    </div>

                    
                    <div id="{{ forloop.counter }}" class="panel-collapse collapse{% if menu_item.active %} in{% endif %}">
                        <div class="panel-body" style="padding-left:10px">
                            
                            {% for sub_menu_item in menu_item.children %}

                            <!-- Child Category -->
                            <form action="{% url 'services:filter' sub_menu_item.id %}" method="get">
                                <p class="sidelinkP">
                                    <button class="sidelinkA" style="padding:0px; margin:0px; border:none; background-color:white" type="submit">
                                        {{ sub_menu_item.name }}<b> ({{ sub_menu_item.service_set.count }})</b>
                                    </button>
                                </p>
                            </form>
                            <!-- End Child Category -->

                            {% endfor %}

                             <!-- See All Link -->
                            <form action="{% url 'services:filter' menu_item.parent.id %}" method="get">
                                <p class="sidelinkP">
                                    <button class="sidelinkA" style="padding:0px; margin:0px; border:none; background-color:white" type="submit">
                                        <b>See All</b>
                                    </button>
                                </p>
                            </form>
                            <!-- End See All Link -->
                            
                        </div>
                    </div>
                    

                </div>
                {% endfor %}
                
            </div>
            <br><br>
        </div>
        <!-- End Left Accordian -->

templates/services/schedule.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block pagename %}Schedule{% endblock %}

{% block content %}
    <div class="container" style="margin-top:135px; margin-bottom 25px">
        <h1 class="text-center" style="font-size:100px"><i style="color:green" class="fa fa-thumbs-up"></i></h1>
        <h2 style="margin-bottom:10px">Your 64007-64253 Throttle Cable Assy is scheduled!</h2> 
        <h3>Your confirmation number is: 1317409872</h3>
        <h5 style="font-weight:300 !important; text-transform:none !important">Please review your details below and contact us if there are any changes in your schedule.</h5>
        <div>
             <h5>Name: <span style="font-weight:300 !important; text-transform:none !important">Name</span></h5>
             <h5>Email: <span style="font-weight:300 !important; text-transform:none !important">email@email.com</span></h5>
             <h5>Telephone: <span style="font-weight:300 !important; text-transform:none !important">(310) 000-0000</span></h5>
             <h5>Address: <span style="font-weight:300 !important; text-transform:none !important">Address Here</span></h5>
             <h5>Zip: <span style="font-weight:300 !important; text-transform:none !important">90000</span></h5>
             <h5>Consultation Day: <span style="font-weight:300 !important; text-transform:none !important">2015-02-07</span></h5>
        </div>                   
    </div>

    <div class="container" style="margin-top:25px; margin-bottom:25px">
        <a href="{% url "home" %}"><div class="btn btn-default" style="margin-right:15px"><i class="fa fa-home"></i>&nbsp;&nbsp;Home</div></a>
        <a href="{% url "services:search" %}"><div class="btn btn-default"><i class="fa fa-tree"></i>&nbsp;&nbsp;More Solutions</div></a>
    </div>
{% endblock %}

templates/services/search.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block pagename %}About{% endblock %}
{% block css %}
    {{ block.super }}
    <link href="{% static "css/search.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="servepic" style="margin-top:80px; width:100%; height:300px">
    </div>
    <br>
    <div class="container" style="margin-bottom:50px">
        <h2 style="text-align:center; margin-top:30px; margin-bottom:20px">Our Solutions</h2>


        {% include 'services/_accordian_menu.html' %}


        <!-- Main Solutions Section -->
        <div class="col-lg-9 col-sm-8 borderkill" style="margin-top:30px">
            <div id="here" style="margin-top:-85px; margin-bottom:85px"></div>
            <h4 style="margin-bottom:0px">Solution List</h4>
            <br><br>

            <form action="{% url "services:search" %}" method="get"><p class="sidelinkP">Displaying: {% if selected %}{{ selected.name }}{% else %}All  Solutions{% endif %} <button type="submit" style="background-color:white; padding:0px; margin:0px; border:none"><i class="fa fa-times"></i></button></p></form>            <div role="tabpanel" class="tab-pane fade in active" id="services">
            <br>

            <div class="row">
                {% for service in services %}
                <div class="col-lg-4 col-sm-6" style="margin-bottom:10px !important">
                    <form action="{% url "services:view" service.slug %}">
                        <button type="submit" style="padding:0px; border:0px; width:100%">
                            <div class="lou_intro_hover photo" style="background-color:#cccccc">
                                <p style="text-align:center">
                                    <img src="{{ MEDIA_URL }}{{ service.image_1 }}" width="100%" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                                </p>
                                <div class="caption">
                                    <div class="blur"></div>
                                    <div class="caption-text">
                                        <h5 style="border-top:2px solid white; border-bottom:2px solid white; padding:10px">{{ service.name }}</h5>
                                        <br><br>
                                        <div class="caption-button">
                                            <h4 style="border-top:2px solid white; border-bottom:2px solid white; padding:10px"><i class="fa fa-plus-square"></i> MORE INFO</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </button>
                    </form>
                </div>
                {% endfor %}

            </div>
        </div>
        <!-- End Main Solutions Section -->

        <!-- Pagination -->
        <div style="text-align:right">
            <p class="sidelinkP2"><b>{{ services.paginator.count }} Total Solutions</b></p> <p class="sidelinkP2"><br>
            {% if services.has_previous %}
                <font size="1"></font></p>
                <a class="sidelinkA" href="?page={{ services.previous_page_number }}&amp;nation=0&amp;cat=1#here">Previous 9</a> &nbsp;&nbsp;&nbsp;&nbsp;
            {% endif %}
            {% if services.has_next %}
                <a class="sidelinkA" href="?page={{ services.next_page_number }}&amp;nation=0&amp;cat=1#here">See Next 9</a>
            {% endif %}
            <p></p></div>
        </div>
        <!-- End Pagination -->

    </div>

{% endblock %}

templates/services/view.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block pagename %}Service{% endblock %}

{% block content %}

    <!-- Image and Description Section -->
    <div class="container" style="margin-bottom:25px; margin-top:100px">
        <div class="row">
            <div class="col-lg-5 col-sm-6" style="margin-top:20px">
                <div role="tabpanel">
                    <br>
                    <!-- Tab panes -->
                    <div class="tab-content">

                        {% if service.image_1 %}
                        <div role="tabpanel" class="tab-pane fade active in" id="pic1">
                            <div class="photo">
                                <img src="{{ MEDIA_URL }}{{ service.image_1 }}" width="100%" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                            </div>
                        </div>
                        {% endif %}

                        {% if service.image_2 %}
                        <div role="tabpanel" class="tab-pane fade" id="pic2">
                            <div class="photo">
                                <img src="{{ MEDIA_URL }}{{ service.image_2 }}" width="100%" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                            </div>
                        </div>
                        {% endif %}

                        {% if service.image_3 %}
                        <div role="tabpanel" class="tab-pane fade" id="pic3">
                            <div class="photo">
                                <img src="{{ MEDIA_URL }}{{ service.image_3 }}" width="100%" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                            </div>
                        </div>
                        {% endif %}

                        {% if service.image_4 %}
                        <div role="tabpanel" class="tab-pane fade" id="pic3">
                            <div class="photo">
                                <img src="{{ MEDIA_URL }}{{ service.image_4 }}" width="100%" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                            </div>
                        </div>
                        {% endif %}

                        {% if service.image_5 %}
                        <div role="tabpanel" class="tab-pane fade" id="pic3">
                            <div class="photo">
                                <img src="{{ MEDIA_URL }}{{ service.image_4 }}" width="100%" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                            </div>
                        </div>
                        {% endif %}

                    </div>

                    <!-- tab list for pictures -->
                    <ul class="list-inline" style="border:none; margin-top:15px" role="tablist">

                        {% if service.image_1 %}
                        <li role="presentation" class="active">
                            <a href="#pic1" aria-controls="pic1" role="tab" data-toggle="tab" class="great_tab">
                                <img src="{{ MEDIA_URL }}{{ service.image_1 }}" width="80px" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                            </a>
                        </li>
                        {% endif %}

                        {% if service.image_2 %}
                        <li role="presentation" class="">
                            <a href="#pic2" aria-controls="pic2" role="tab" data-toggle="tab" class="great_tab">
                                <img src="{{ MEDIA_URL }}{{ service.image_2 }}" width="80px" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                            </a>
                        </li>
                        {% endif %}

                        {% if service.image_3 %}
                        <li role="presentation" class="">
                            <a href="#pic3" aria-controls="pic3" role="tab" data-toggle="tab" class="great_tab">
                                <img src="{{ MEDIA_URL }}{{ service.image_3 }}" width="80px" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                            </a>
                        </li>
                        {% endif %}

                        {% if service.image_4 %}
                        <li role="presentation" class="">
                            <a href="#pic4" aria-controls="pic4" role="tab" data-toggle="tab" class="great_tab">
                                <img src="{{ MEDIA_URL }}{{ service.image_4 }}" width="80px" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                            </a>
                        </li>
                        {% endif %}

                        {% if service.image_5 %}
                        <li role="presentation" class="">
                            <a href="#pic1" aria-controls="pic5" role="tab" data-toggle="tab" class="great_tab">
                                <img src="{{ MEDIA_URL }}{{ service.image_5 }}" width="80px" class="img-responsive" alt="64007-64253 Throttle Cable Assy">
                            </a>
                        </li>
                        {% endif %}

                    </ul>

                </div>
            </div>

            <div class="col-lg-7 col-sm-6" style="margin-top:40px">
                <h2 style="margin-bottom:10px">{{ service.name }}</h2>
                <h5 style="margin-bottom:15px">Schedule a free inspection today!</h5>
                <a class="page-scroll" href="#schedule"><div class="btn btn-default"><i class="fa fa-calendar"></i>&nbsp;&nbsp;Schedule</div></a>
                <p class="retail" style="margin-top:30px"><b>What We Provide:</b> {{ service.description }}</p>
            </div>
        </div>
    </div>
    <!-- End Image and Description Section -->


    <!-- Identification Guide and Related Services Section -->
    <div class="container" style="margin-top:20px; margin-bottom:25px">
        <div role="tabpanel">
            <br>
            <!-- tab list for pictures -->
            <ul class="nav nav-tabs no_display" role="tablist">
                <li role="presentation" class="active">
                    <a href="#moreinfo" aria-controls="moreinfo" role="tab" data-toggle="tab" class="great_tab">
                        <h5 style="margin-bottom:10px">
                            Identification Guide
                        </h5>
                    </a>
                </li>
                {% if service.related_services.all %}
                <li role="presentation" class="get-active">
                    <a href="#label" aria-controls="label" role="tab" data-toggle="tab" class="great_tab">
                        <h5 style="margin-bottom:10px">
                            Related Services
                        </h5>
                    </a>
                </li>
                {% endif %}
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane fade in active" id="moreinfo">
                    <br>
                    <p class="retail"><b>You Need {{ service.name }} If:</b> {{ service.identification_guide}}</p>
                </div>

                <div role="tabpanel" class="tab-pane fade" id="label">

                    {% for related_service in service.related_services.all %}
                    <br>
                    <h4 style="margin-bottom:10px">{{ related_service.name }}</h4>
                    <p class="retail">{{ related_service.description }}</p>
                    <br>
                    <form action="{% url 'services:view' related_service.slug %}" method="get">
                        <button type="submit" class="btn btn-default"><i class="fa fa-eye"></i>&nbsp;&nbsp;View Solution</button>
                    </form>
                    {% endfor %}

                </div>

            </div>
        </div>
    </div>
    <!-- Identification Guide and Related Services Section -->


    <!-- Related Products -->
    <div class="container" style="margin-top:20px; margin-bottom 25px; ">
        <hr>
        <h4 style="margin-bottom:10px">Do it Yourself Products Related to {{ service.name }}:</h4>
        <h5 style="color:rgba(153,0,0,1)">free shipping on all products!</h5>
        <div class="row">

            {% for product in service.related_products.all %}

                {% include 'shop/_single_product.html' with product=product %}

            {% endfor %}

        </div>
    </div>
    <!-- End Related Products -->


    <!-- Schedule Consultation -->
    <div class="container" style="margin-top:20px; margin-bottom 25px">
        <h4>Schedule a free {{ service.name }}:</h4>
        <div class="row">
            <form action="" name="service" onsubmit="return validateService()" method="post">
            {% csrf_token %}
                <div class="col-lg-6">
                    <h5 style="margin-bottom:10px">Contact Information <font color="#FF0000">*</font></h5>
                    <input type="text" name="name" placeholder="Enter Your Name" class="form-control" value=""><br>
                    <input type="email" name="email" placeholder="Enter Your Email" class="form-control" value=""><br>
                    <input type="tel" id="phone" name="phone" placeholder="Phone Number: (XXX) XXX-XXXX" class="form-control" value=""><br>
                </div>
                <div class="col-lg-6">
                    <h5 style="margin-bottom:10px">Inspection Information</h5>
                    <input type="text" name="address" placeholder="Enter Your Address" class="form-control" value=""><br>
                    <input type="text" id="zip" name="zip" placeholder="Enter Your Zip Code" class="form-control" value=""><br>
                    <input type="text" name="date" placeholder="Select a Date for Inspection" class="form-control datepicker" value=""><br>
                    <button class="btn btn-default btn-lg" type="submit" name="schedule" value="84" style="margin-top:10px; margin-bottom:100px"><i class="fa fa-thumbs-up"></i>&nbsp;Submit</button>
                </div>
            </form>
        </div>

    </div>
    <!-- End Schedule Consultation -->

{% endblock %}

{% block javascript %}

    {{ block.super }}

    <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>

    <script>
        $('.datepicker').datepicker({
            format: 'yyyy-mm-dd',
            daysOfWeekDisabled: "0",
            todayHighlight: true
        });
    </script>

    <div class="datepicker dropdown-menu">
        <div class="datepicker-days" style="display: block;">
            <table class=" table-condensed">
                <thead>
                    <tr><th class="prev">‹</th><th colspan="5" class="switch">February 2015</th><th class="next">›</th></tr><tr><th class="dow">Su</th><th class="dow">Mo</th><th class="dow">Tu</th><th class="dow">We</th><th class="dow">Th</th><th class="dow">Fr</th><th class="dow">Sa</th></tr>
                </thead>
                <tbody>
                    <tr><td class="day  old">25</td><td class="day  old">26</td><td class="day  old">27</td><td class="day  old">28</td><td class="day  old">29</td><td class="day  old">30</td><td class="day  old">31</td></tr><tr><td class="day ">1</td><td class="day ">2</td><td class="day ">3</td><td class="day ">4</td><td class="day ">5</td><td class="day ">6</td><td class="day ">7</td></tr><tr><td class="day ">8</td><td class="day ">9</td><td class="day ">10</td><td class="day ">11</td><td class="day ">12</td><td class="day ">13</td><td class="day  active">14</td></tr><tr><td class="day ">15</td><td class="day ">16</td><td class="day ">17</td><td class="day ">18</td><td class="day ">19</td><td class="day ">20</td><td class="day ">21</td></tr><tr><td class="day ">22</td><td class="day ">23</td><td class="day ">24</td><td class="day ">25</td><td class="day ">26</td><td class="day ">27</td><td class="day ">28</td></tr><tr><td class="day  new">1</td><td class="day  new">2</td><td class="day  new">3</td><td class="day  new">4</td><td class="day  new">5</td><td class="day  new">6</td><td class="day  new">7</td></tr>
                </tbody>
            </table>
        </div>
        <div class="datepicker-months" style="display: none;">
            <table class="table-condensed">
                <thead><tr><th class="prev">
                    ‹</th><th colspan="5" class="switch">2015</th><th class="next">›</th></tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="7"><span class="month">Jan</span><span class="month active">Feb</span><span class="month">Mar</span><span class="month">Apr</span><span class="month">May</span><span class="month">Jun</span><span class="month">Jul</span><span class="month">Aug</span><span class="month">Sep</span><span class="month">Oct</span><span class="month">Nov</span><span class="month">Dec</span></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="datepicker-years" style="display: none;">
            <table class="table-condensed">
                <thead>
                    <tr><th class="prev">‹</th><th colspan="5" class="switch">2010-2019</th><th class="next">›</th></tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="7"><span class="year old">2009</span><span class="year">2010</span><span class="year">2011</span><span class="year">2012</span><span class="year">2013</span><span class="year">2014</span><span class="year active">2015</span><span class="year">2016</span><span class="year">2017</span><span class="year">2018</span><span class="year">2019</span><span class="year old">2020</span></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}