agriturf_supplies/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'agriturf_supplies.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'content.views.home', name='home'),
    (r'^content/', include('content.urls', app_name='content', namespace="content")),
    (r'^services/', include('services.urls', app_name='services', namespace="services")),
    (r'^shop/', include('shop.urls', app_name='shop', namespace="shop")),
    (r'^newsletter/', include('newsletter.urls', app_name='newsletter', namespace="newsletter")),

)

# don't run static files in production!!
if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
            url(r'^static/(?P<path>.*)$', 'serve'),
        )

    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
    )

# Configuration for admin Title:
admin.site.site_header = 'Agriturf Administration'

services/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('agriturf_supplies.services.views',

    #(r'^index/$', views.home), # main urls.py maps this directly to /
    url(r'^schedule/$', views.schedule, name='schedule'),
    url(r'^browse/$', views.search, name='search'),
    url(r'^browse/(\d+)$', views.search, name='filter'),
    url(r'^solution/(?P<slug>.*)$', views.view, name='view'),

)

shop/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('agriturf_supplies.services.views',

    #(r'^index/$', views.home), # main urls.py maps this directly to /
    url(r'^product/(?P<slug>.*)$', views.product, name='view_product'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^checkout/$', views.checkout, name='start_checkout'),
    url(r'^checkout/(\d+)$', views.checkout, name='checkout_step'),

)

shop/models.py
import itertools

from django.db import models
from django.utils.text import slugify
from random import randint


class Product(models.Model):

    name = models.CharField(max_length=500)
    slug = models.CharField(max_length=500, blank=True, null=True)
    description = models.TextField()
    size = models.CharField(max_length=255, blank=True)
    label = models.FileField(upload_to='products/product_labels/', blank=True)
    msds_label = models.FileField(upload_to='products/msds_labels/', blank=True)
    product_price = models.DecimalField(max_digits=5, decimal_places=2)
    sale_price = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    on_sale = models.BooleanField(default=False)
    organic = models.BooleanField(default=False)
    image_1 = models.FileField(upload_to='products/images/')
    image_2 = models.FileField(upload_to='products/images/', blank=True)
    image_3 = models.FileField(upload_to='products/images/', blank=True)
    image_4 = models.FileField(upload_to='products/images/', blank=True)
    image_5 = models.FileField(upload_to='products/images/', blank=True)
    manufacturer_name = models.CharField(max_length=255)
    manufacturer_website = models.URLField(max_length=255, blank=True)
    rate_combo = models.CharField(max_length=255, blank=True)

    @property
    def current_price(self):
        if self.on_sale:
            return self.sale_price
        else:
            return self.product_price

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        """
        Creating unique slug on save by adding an integer if it
        already exists.
        """
        self.slug = original = slugify(self.name)
        for x in itertools.count(2):
            if not Product.objects.filter(slug=self.slug).exists():
                break
            self.slug = '%s-%d' % (original, x)
        super(Product, self).save(*args, **kwargs)


class Order(models.Model):

    order_number = models.IntegerField()
    order_type = models.CharField(max_length=15)
    for_pickup = models.BooleanField(default=False)
    scheduled = models.DateField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    order_total = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    number_of_products = models.IntegerField(blank=True, null=True)
    service = models.ForeignKey('services.service', blank=True, null=True)
    send_labels = models.BooleanField(default=False)
    #description = models.TextField()
    name = models.CharField(max_length=255)
    email = models.EmailField()
    phone = models.CharField(max_length=255, blank=True)
    address1 = models.CharField(max_length=255, blank=True)
    address2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    state = models.CharField(max_length=2, blank=True)
    zip_code = models.CharField(max_length=5, blank=True)
    products = models.ManyToManyField('product')

    def save(self, *args, **kwargs):
        # generate random order number not in db
        while not self.order_number:
            random_number = randint(100000,999999)
            if not Order.objects.filter(order_number=random_number):
                self.order_number = random_number
        super(Order, self).save(*args, **kwargs)

    def __unicode__(self):
        return "%s - Order # %s - %s" % (self.created.strftime("%m.%d.%y"), self.order_number, self.name)


class Cart(object):
    def __init__(self, request):
        self.request = request
        # init cart session object if not set
        if not request.session.get('cart'):
            request.session['cart'] = {}
        self.cart = self.request.session['cart']

    def adjust(self,item, quantity):
        item = str(item)
        quantity = int(quantity)

        current_quantity = self.get_item_quantity_in_cart(item)
        self.cart[item] = current_quantity + quantity

        self.clean_cart()
        self.set_cart_quantity()
        self.save_to_session()

    def get_item_quantity_in_cart(self,item):
        try:
            return self.cart[item]
        except KeyError:
            return 0

    @property
    def items(self):
        self.clean_cart()
        self.set_cart_quantity()
        return self.quantity

    def set_cart_quantity(self):
        quantity = sum(v for k, v in self.cart.items())
        self.quantity = quantity

    def clean_cart(self):
        # cleans out items with quantity of 0
        for k,v in self.cart.items():
            if v <= 0:
                self.cart.pop(k)

    def save_to_session(self):
        self.request.session['cart'] = self.cart
        self.request.session['cart_quantity'] = self.quantity
        self.request.session['cart_subtotal'] = Cart.get_product_total_cost(self.request)

    @classmethod
    def get_cart_contents(cls, request):
        cart_items = []
        item_ids = [k for k in request.session['cart']]
        products = Product.objects.filter(pk__in=item_ids)

        for k,v in request.session['cart'].items():
            obj = [ i for i in products if i.id==int(k)][0]
            item = {'product': obj, 'quantity': v, 'price_of_quantity': obj.current_price * v }
            cart_items.append(item)

        return cart_items

    @classmethod
    def get_product_total_cost(cls, request):
        cart_items = cls.get_cart_contents(request)
        subtotal = 0.00
        for item in cart_items:

            product = item["product"].current_price * item['quantity']
            subtotal += float(product)
        return subtotal

shop/forms.py
from django import forms

class CheckoutStepOne(forms.Form):
    name = forms.CharField()
    email = forms.CharField()
    phone = forms.CharField()
    address1 = forms.CharField()
    address2 = forms.CharField(required=False)
    city = forms.CharField()
    state = forms.CharField()
    zip_code = forms.CharField()

class AdjustCartQuantity(forms.Form):
    action = forms.CharField()
    quantity = forms.IntegerField()
    item_number = forms.IntegerField()

    def clean_action(self):
        if not self.cleaned_data['action'] == "adjust_quantity":
            raise forms.ValidationError("Invalid Action")

shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import Template
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from models import Product, Cart
from forms import CheckoutStepOne, AdjustCartQuantity

# Create your views here.

def product(request, slug):
    product = Product.objects.get(slug=slug)
    savings = 100 - (product.sale_price / product.product_price)*100

    return render(request, 'shop/product.html', {"product":product, 'savings':savings})

def cart(request):
    cart = Cart(request)

    # user is adjusting quantity
    adjust_cart_quantity = AdjustCartQuantity(request.POST)
    if adjust_cart_quantity.is_valid():
        cart.adjust(adjust_cart_quantity.cleaned_data['item_number'], adjust_cart_quantity.cleaned_data['quantity'])

    cart_items = Cart.get_cart_contents(request)

    return render(request, 'shop/cart.html', {'page':'cart', 'cart_items':cart_items})

def checkout(request, step=1):
    ##bounce user back to cart if no products in cart
    if not Cart(request).items:
        return redirect(reverse('shop:cart'))

    step = int(step)
    if step == 1:
        cart_items = Cart.get_cart_contents(request)
        #cart_subtotal = Cart.get_product_total_cost(request)

        return render(request, 'shop/checkout_step_1.html', {'page':'cart', 'cart_items':cart_items})

    elif step == 2:
        form = CheckoutStepOne(request.POST)
        if form.is_valid():
            # save form data to session
            request.session['user_info'] = form.cleaned_data
        else:
            return redirect(reverse('shop:start_checkout'))

        return render(request, 'shop/checkout_step_2.html', {'page':'cart'})

templates/shop/_product_details.html
            <!-- Product Info -->
            <div class="col-lg-7 col-sm-6" style="margin-top:40px">
                <h2 style="margin-bottom:10px">{{ product.name }}</h2>

                <h5 style="margin-bottom:15px">
                    {%if product.manufacturer_name %}
                        By {%if product.manufacturer_website %}<a href="{{ product.manufacturer_website }}">{% endif %}{{ product.manufacturer_name }}</a>
                    {% endif %}
                </h5>

                <div style="margin-bottom:20px">
                    <form action="{% url 'shop:cart' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="adjust_quantity">
                        <label>
                            <p class="retail" style="font-size:smaller">QUANTITY</p>
                            <input type="number" name="quantity" value="1" style="width:70px" class="form-control">
                        </label>
                        <button type="submit" value="{{ product.id }}" name="item_number" class="btn btn-default" style="margin-left:10px; margin-top:-7px"><i class="fa fa-shopping-cart"></i>&nbsp;&nbsp;Add to Cart</button>
                    </form>
                </div>

                {%if product.on_sale %}
                <p class="retail-less">Price: ${{ product.product_price }}</p>
                <p class="sale">Sale Price: ${{ product.sale_price }}</p>
                {% else %}
                <p class="retail">Price: ${{ product.product_price }}</p>
                {% endif %}

                <p class="retail" style="font-size:smaller; margin-top:5px">&amp; FREE SHIPPING! 
                    {%if product.on_sale %}<span class="sale" style="font-size:small">You save {{ savings|floatformat:"0" }}%</span>{% endif %}
                </p>
                <br>

                <p class="retail"><b>Product Description:</b> {{ product.description }}</p>
            </div>
            <!-- End Product Info -->

templates/shop/_product_images_widget.html
                <div role="tabpanel">
                    <br>
                    <!-- Tab panes -->
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active" id="pic1">
                            <div class="photo">
                                <img src="{{ MEDIA_URL }}{{ product.image_1 }}" width="100%" class="img-responsive" alt="Product E">
                            </div>
                        </div>

                        {% if product.image_2 %}
                        <div role="tabpanel" class="tab-pane fade" id="pic2">
                            <div class="photo">
                                <img src="{{ MEDIA_URL }}{{ product.image_2 }}" width="100%" class="img-responsive" alt="Product E">
                            </div>
                        </div>
                        {% endif %}

                        {% if product.image_3 %}
                        <div role="tabpanel" class="tab-pane fade" id="pic3">
                            <div class="photo">
                                <img src="{{ MEDIA_URL }}{{ product.image_2 }}" width="100%" class="img-responsive" alt="Product E">
                            </div>
                        </div>
                        {% endif %}

                        {% if product.image_4 %}
                        <div role="tabpanel" class="tab-pane fade" id="pic4">
                            <div class="photo">
                                <img src="{{ MEDIA_URL }}{{ product.image_2 }}" width="100%" class="img-responsive" alt="Product E">
                            </div>
                        </div>
                        {% endif %}

                        {% if product.image_5 %}
                        <div role="tabpanel" class="tab-pane fade" id="pic5">
                            <div class="photo">
                                <img src="{{ MEDIA_URL }}{{ product.image_2 }}" width="100%" class="img-responsive" alt="Product E">
                            </div>
                        </div>
                        {% endif %}

                    </div>

                    <!-- tab list for pictures -->
                    <ul class="list-inline" style="border:none" role="tablist">

                        <li role="presentation" class="active"><a href="#pic1" aria-controls="pic1" role="tab" data-toggle="tab" class="great_tab"><img src="{{ MEDIA_URL }}{{ product.image_1 }}" width="80px" class="img-responsive" alt="Product E"></a></li>

                        {% if product.image_2 %}
                        <li role="presentation"><a href="#pic2" aria-controls="pic2" role="tab" data-toggle="tab" class="great_tab"><img src="{{ MEDIA_URL }}{{ product.image_2 }}" width="80px" class="img-responsive" alt="Product E"></a></li>
                        {% endif %}

                        {% if product.image_3 %}
                        <li role="presentation"><a href="#pic3" aria-controls="pic3" role="tab" data-toggle="tab" class="great_tab"><img src="{{ MEDIA_URL }}{{ product.image_3 }}" width="80px" class="img-responsive" alt="Product E"></a></li>
                        {% endif %}

                        {% if product.image_4 %}
                        <li role="presentation"><a href="#pic4" aria-controls="pic4" role="tab" data-toggle="tab" class="great_tab"><img src="{{ MEDIA_URL }}{{ product.image_4 }}" width="80px" class="img-responsive" alt="Product E"></a></li>
                        {% endif %}

                        {% if product.image_5 %}
                        <li role="presentation"><a href="#pic5" aria-controls="pic5" role="tab" data-toggle="tab" class="great_tab"><img src="{{ MEDIA_URL }}{{ product.image_5 }}" width="80px" class="img-responsive" alt="Product E"></a></li>
                        {% endif %}

                    </ul>
                    <!-- End tab list for pictures -->
                </div>

templates/shop/_product_more_information_tabs.html
    <!-- More Information and Product Labels -->
    <div class="container" style="margin-top:20px; margin-bottom:25px">
        <div role="tabpanel">
            <br>
            <!-- tab list for pictures -->
            <ul class="nav nav-tabs no_display" role="tablist">

                <li role="presentation" class="active">
                    <a href="#moreinfo" aria-controls="moreinfo" role="tab" data-toggle="tab" class="great_tab">
                        <h5 style="margin-bottom:10px">
                            More Information
                        </h5>
                    </a>
                </li>
                {% if product.label or product.msds_label %}
                <li role="presentation">
                    <a href="#label" aria-controls="label" role="tab" data-toggle="tab" class="great_tab">
                        <h5 style="margin-bottom:10px">
                            Product Label(s)
                        </h5>
                    </a>
                </li>
                {% endif %}

            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div role="tabpanel" class="tab-pane fade in active" id="moreinfo">
                    <br>
                    <p class="retail"><b>Rate &amp; Combination:</b> {{ product.rate_combo }}</p>
                    <p class="retail"><b>Size/Quantity:</b> {{ product.size }}</p>
                </div>
                <div role="tabpanel" class="tab-pane fade" id="label">

                    <h5 style="margin-top:25px">
                        Click on the button(s) below to view, download, or print the label(s).
                    </h5>

                    {% if product.label %}
                    <a href="{{ MEDIA_URL }}{{ product.label }}"><div class="btn btn-default" style="margin-right:20px"><i class="fa fa-newspaper-o"></i>&nbsp;&nbsp;Product Label</div></a>
                    {% endif %}

                    {% if product.msds_label %}
                    <a href="{{ MEDIA_URL }}{{ product.msds_label }}"><div class="btn btn-default"><i class="fa fa-newspaper-o"></i>&nbsp;&nbsp;MSDS Label</div></a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
    <!-- End More Information and Product Labels -->

templates/shop/_product_related.html
    <!-- Related Products -->
    <div class="container" style="margin-top:20px; margin-bottom 25px; ">
        <hr>
        <h4>People Who Bought Product E Also Considered:</h4> 
        <div class="row">

            <div class="col-lg-3 col-xs-6 button_show" style="margin-bottom:10px !important">
                <form action="{% url 'shop:view_product' 'product-a' %}" method="GET">
                    <button type="submit" style="padding:0px; border:0px">
                        <div class="border-bottom" style="background-color:white">
                            <div class="photo">
                                <img src="/media/products/images/1.png" width="100%" class="img-responsive" alt="Product A">
                            </div>
                            <div class="text-center"> 
                                <h4 style="margin-top:20px; margin-bottom:10px">Product A</h4>
                                <p style="margin-bottom:5px; font-size:110%" ="">64 ounces: <b><font style="color:rgba(153,0,0,1)">$36.45</font></b></p>
                                <h5 style="margin-top:0px; margin-bottom:5px"><b><font style="color:rgba(153,0,0,1)"><br></font></b></h5>
                            </div>
                        </div>
                    </button>
                </form>
            </div>

            <div class="col-lg-3 col-xs-6 button_show" style="margin-bottom:10px !important">
                <form action="{% url 'shop:view_product' 'product-b' %}" method="GET">
                    <button type="submit" style="padding:0px; border:0px">
                        <div class="border-bottom" style="background-color:white">
                            <div class="photo">
                                <img src="/media/products/images/6.png" width="100%" class="img-responsive" alt="Product F">
                            </div>
                            <div class="text-center"> 
                                <h4 style="margin-top:20px; margin-bottom:10px">Product F</h4>
                                <p style="margin-bottom:5px; font-size:110%" ="">5 traps: <b><font style="color:rgba(153,0,0,1)">$15.00</font></b></p>
                                <h5 style="margin-top:0px; margin-bottom:5px"><b><font style="color:rgba(153,0,0,1)">ON SALE!</font></b></h5>
                            </div>
                        </div>
                    </button>
                </form>
            </div>

            <div class="col-lg-3 col-xs-6 button_show" style="margin-bottom:10px !important">
                <form action="{% url 'shop:view_product' 'product-c' %}" method="GET">
                    <button type="submit" style="padding:0px; border:0px">
                        <div class="border-bottom" style="background-color:white">
                            <div class="photo">
                                <img src="/media/products/images/7.png" width="100%" class="img-responsive" alt="Product G">
                            </div>
                            <div class="text-center"> 
                                <h4 style="margin-top:20px; margin-bottom:10px">Product G</h4>
                                <p style="margin-bottom:5px; font-size:110%" ="">1 hawk: <b><font style="color:rgba(153,0,0,1)">$10.80</font></b></p>
                                <h5 style="margin-top:0px; margin-bottom:5px"><b><font style="color:rgba(153,0,0,1)">ON SALE!</font></b></h5>
                            </div>
                        </div>
                    </button>
                </form>
            </div>

            <div class="col-lg-3 col-xs-6 button_show" style="margin-bottom:10px !important">
                <form action="{% url 'shop:view_product' 'product-d' %}" method="GET">
                    <button type="submit" style="padding:0px; border:0px">
                        <div class="border-bottom" style="background-color:white">
                            <div class="photo">
                                <img src="/media/products/images/8.png" width="100%" class="img-responsive" alt="Product H">
                            </div>
                            <div class="text-center"> 
                                <h4 style="margin-top:20px; margin-bottom:10px">Product H</h4>
                                <p style="margin-bottom:5px; font-size:110%" ="">10 gallons: <b><font style="color:rgba(153,0,0,1)">$3.00</font></b></p>
                                <h5 style="margin-top:0px; margin-bottom:5px"><b><font style="color:rgba(153,0,0,1)"><br></font></b></h5>
                            </div>
                        </div>
                    </button>
                </form>
            </div>

        </div>                   
    </div>
    <!-- End Related Products -->

templates/shop/_single_product.html
{% if format == "checkout" %}
            <div class="col-lg-3 col-xs-6 button_show" style="margin-bottom:10px !important">
                <div class="border-bottom">
                    <div class="photo">
                        <img src="{{ MEDIA_URL}}{{ product.image_1 }}" width="100%" class="img-responsive" alt="a">
                    </div>
                    <div class="text-center"> 
                        <b>{{ product.name }}</b>
                        <p style="margin-bottom:0px; font-size:110%;">{{ product.size }}: <b><font style="color:rgba(153,0,0,1)">{% if product.on_sale %}${{ product.sale_price }}{% else %}${{ product.product_price }}{% endif %}</font></b></p> 
                        <b>Quantity: {{ quantity }}</b>
                        <hr style="margin:5px">
                        <h5 style="margin-top:15px; margin-bottom:15px">Change Quantity</h5>
                        <form action="{% url 'shop:cart'  %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="adjust_quantity">
                            <div style="margin-left:8%; margin-right:8%" class="input-group text-center">
                                <input min="-{{ quantity }}" style="border-radius:0px !important" type="number" name="quantity" value="{{ quantity }}" class="form-control">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" style="border-radius:0px !important" type="submit" name="item_number" value="{{ product.id }}">+ / -</button>
                                </span>
                            </div>
                        </form>
                        <br>
                    </div>
                </div>
            </div>
{% else %}
            <div class="col-lg-3 col-xs-6 button_show" style="margin-bottom:10px !important">
                <form action="{% url 'shop:view_product' product.slug %}" method="GET">
                    <button type="submit" style="padding:0px; border:0px">
                        <div class="border-bottom" style="background-color:white">
                            <div class="photo">
                                <img src="{{ MEDIA_URL}}{{ product.image_1 }}" width="100%" class="img-responsive" alt="Product E">
                            </div>
                            <div class="text-center"> 
                                <h4 style="margin-top:20px; margin-bottom:10px">{{ product.name }}</h4>
                                <p style="margin-bottom:5px; font-size:110%">{{ product.size }}: 
                                    <b><font style="color:rgba(153,0,0,1)">{% if product.on_sale %}${{ product.sale_price }}{% else %}${{ product.product_price }}{% endif %}</font></b>
                                </p>
                                <h5 style="margin-top:0px; margin-bottom:5px">
                                    <b><font style="color:rgba(153,0,0,1)">{% if product.on_sale %}ON SALE!{% else %}<br>{% endif %}</font></b>
                                </h5>
                            </div>
                        </div>
                    </button>
                </form>
            </div>
{% endif %}

templates/shop/cart.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block pagename %}About{% endblock %}


{% block content %}
    {% if not request.session.cart_quantity %}
    <!-- Empty Cart -->
    <div class="container" style="margin-top:135px; margin-bottom 25px">
        <p class="text-center" style="font-size:85px; color:rgba(153,0,0,1)"><i class="fa fa-warning"></i></p>
        <h2 style="margin-bottom:40px">You have no items in your shopping cart.</h2> 
        <h5>Click on solutions and select one to view the do it yourself products to solve your agricultural issues.</h5>
        <a href="{% url "services:search" %}"><div style="margin-bottom:100px" class="btn btn-default"><i class="fa fa-tree"></i>&nbsp;&nbsp;View Solutions</div></a>
    </div>
    <!-- End Empty Cart -->
    {% endif %}
    

    {% if request.session.cart_quantity %}
    <!-- Products In Cart -->
    <div class="container" style="margin-top:135px; margin-bottom 25px">

        <h2 style="margin-bottom:10px">Items in your shopping cart:</h2> 
        <h5>You have {{ request.session.cart_quantity }} items in your shopping cart.</h5>
        <div class="row" style=" ">

            {% for item in cart_items %}
                {% include 'shop/_single_product.html' with product=item.product quantity=item.quantity format="checkout" %}
            {% endfor %}

        </div>                   
    </div>
    <!-- End Products In Cart -->
    {% endif %}


    <!-- Free Shipping -->
    <div class="container" style="margin-top:25px; margin-bottom:25px; ">
        <h4 style="color:rgba(153,0,0,1); margin-bottom:10px">Free shipping on your order!</h4>
        <a href="{% url "shop:start_checkout" %}"><div class="btn btn-default" style="margin-right:15px; margin-bottom:10px"><i class="fa fa-thumbs-up"></i>&nbsp;&nbsp;Proceed to Checkout</div></a>
        <a href="{% url "services:search" %}"><div class="btn btn-default" style="margin-bottom:10px"><i class="fa fa-tags"></i>&nbsp;&nbsp;Continue Shopping</div></a>
    </div>
    <!-- End Free Shipping -->


    <!-- Reserve For Pickup -->
    <div class="container" style="  margin-top:50px; margin-bottom:25px; ">
        <h4>Or, reserve these items for an in-store pickup below</h4>
        <form action="" name="pickup" onsubmit="return validatePickup()" method="post">
            <div class="col-lg-6">
                <input type="text" name="name" placeholder="Enter Your Name (required)" class="form-control" value=""><br>
                <input type="email" name="email" placeholder="Enter Your Email (required)" class="form-control" value=""><br>
            </div>
            <div class="col-lg-6">
                <input type="tel" id="phone" name="telephone" placeholder="Enter Your Phone Number" class="form-control" value=""><br>
                <input type="text" name="date" placeholder="Date for Pickup" class="form-control datepicker" value=""><br>
            </div>
            <button class="btn btn-default btn-lg" type="submit" value="submit" name="pickup" style="margin-top:10px; margin-bottom:100px"><i class="fa fa-thumbs-up"></i>&nbsp;Submit</button>
        </form>
    </div>
    <!-- End Reserve For Pickup -->

{% endblock %}

templates/shop/product.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% block pagename %}Service{% endblock %}

{% block content %}

    <!-- Product Image and Description -->
    <div class="container" style="margin-bottom:25px; margin-top:100px">
        <div class="row">
            <div class="col-lg-5 col-sm-6" style="margin-top:40px">
                {% include 'shop/_product_images_widget.html' %}
            </div>

            {% include 'shop/_product_details.html' %}

        </div>

        <div class="organic">
            {% if product.organic %}
            <img src="{% static 'img/orgbadge.png' %}" class="orgimg" alt="Organic Product">
            {% endif %}
        </div>

    </div>

    {% include 'shop/_product_more_information_tabs.html' %}

    {% include 'shop/_product_related.html' %}

    <br>
    <br>
   
{% endblock %}