agriturf_supplies/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'agriturf_supplies.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'content.views.home', name='home'),
    (r'^content/', include('content.urls', app_name='content', namespace="content")),
    (r'^services/', include('services.urls', app_name='services', namespace="services")),
    (r'^shop/', include('shop.urls', app_name='shop', namespace="shop")),
    (r'^newsletter/', include('newsletter.urls', app_name='newsletter', namespace="newsletter")),

)

# don't run static files in production!!
if settings.DEBUG:
    urlpatterns += patterns('django.contrib.staticfiles.views',
            url(r'^static/(?P<path>.*)$', 'serve'),
        )

    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
    )

# Configuration for admin Title:
admin.site.site_header = 'Agriturf Administration'

content/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('agriturf_supplies.content.views',

    #(r'^index/$', views.home), # main urls.py maps this directly to /
    url(r'^about/$', views.about, name='about'),
    url(r'^careers/$', views.careers, name='careers'),
    url(r'^terms_of_use/$', views.terms_of_use, name='terms_of_use'),
    url(r'^send_message/$', views.send_message, name='send_message'),
)

newsletter/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('agriturf_supplies.services.views',

    url(r'^subscribe/$', views.subscribe, name='subscribe'),
    url(r'^unsubscribe/$', views.unsubscribe, name='unsubscribe'),

)

services/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('agriturf_supplies.services.views',

    #(r'^index/$', views.home), # main urls.py maps this directly to /
    url(r'^schedule/$', views.schedule, name='schedule'),
    url(r'^browse/$', views.search, name='search'),
    url(r'^browse/(\d+)$', views.search, name='filter'),
    url(r'^solution/(?P<slug>.*)$', views.view, name='view'),

)

shop/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('agriturf_supplies.services.views',

    #(r'^index/$', views.home), # main urls.py maps this directly to /
    url(r'^product/(?P<slug>.*)$', views.product, name='view_product'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^checkout/$', views.checkout, name='start_checkout'),
    url(r'^checkout/(\d+)$', views.checkout, name='checkout_step'),

)

templates/_footer.html
{% load static from staticfiles %}

    <!-- Social Share -->
    <div id="here" class="container" style="background-color:black; width: 100%; height:40px; padding-top:5px">
        <div class="row">
            <div class="col-lg-12 text-center" style="margin-top: 5px; margin-bottom:5px; overflow:hidden"><p class="sharer">
                <a href="https://www.facebook.com/sharer/sharer.php?s=100&p[url]=https://www.agriturfsupplies.com" class="sharer"><i class="fa fa-facebook"></i></a>&nbsp;&nbsp;
                <a href="http://twitter.com/share?text=Check out the NEW Agri-Turf Supplies: &url=https://www.agriturfsupplies.com&hashtags=growmore,santabarbara,805living " class="sharer"><i class="fa fa-twitter"></i></a>&nbsp;&nbsp;
                <font style="color:white"> - SHARE - </font>&nbsp;&nbsp;
                <a href="https://plus.google.com/share?url=www.agriturfsupplies.com" class="sharer"><i class="fa fa-google"></i></a>&nbsp;&nbsp;
                <a href="http://www.linkedin.com/shareArticle?mini=true&url=https://www.agriturfsupplies.com&title=Check out the NEW Agri-Turf Supplies!&summary=Agri-Turf Supplies, Inc. is Santa Barbara's agricultural and pest control supplier. Visit its site to learn more.&source=The Agri-Turf Supplies Team" class="sharer"><i class="fa fa-linkedin"></i></a>    
            </p></div>
        </div>
    </div>
    <!-- End Social Share -->

    <!-- Newsletter -->
    <div class="container" style="background-color:rgba(153,153,153,.6); width: 100%; height:230px; padding-top:5px">
        <div class="text-center">
                <h3 class="taller">Join Our Newsletter</h3>
                <!--Subscribe Bar-->    
                <form name="addEmail" action="{% url "newsletter:subscribe" %}" onsubmit="return validateNewsletter()" method="POST">
                {% csrf_token %}
                <div style="margin-left:auto; margin-right:auto" class="input-group text-center special_width">
                    <input style="border-radius:0px !important" type="text" name="email" value="" placeholder="Subscribe" class="form-control">
                    <span class="input-group-btn">
                    <button class="btn btn-default" style="border-radius:0px !important"  type="submit" name="e_list" value="1"><i class="fa fa-thumbs-up"></i></button>
                    </span>
                </div>
                </form>
                <p class="news">Sign me up to receive emails on new product arrivals, special offers, and exclusive events.</p>
                <!--End of Subscribe Bar-->
        </div>
    </div>
    <!-- End Newsletter -->
    
    <footer id="contact">
        <div class="container text-center">
            <h2>Contact Us</h2>
            <div class="row">
                <div class="col-lg-6">
                    <p><b>Retail & Service Center</b></p>
                    <p>2257 Las Positas Road, Santa Barbara, CA 93105</p>
                    <p><b>Telephone:</b> (805) 569-2257</p>
                    <p><b>Email:</b> info@agriturfsupplies.com</p>
                </div>
                <div class="col-lg-6">
                    <p><b>Hours</b></p>
                    <p><b>Monday - Friday:</b> 7:00 am - 4:30 pm</p>
                    <p><b>Saturday:</b> 7:00 am - 4:30 pm</p>
                    <p><b>Sunday:</b> Closed</p>
                </div>
            </div>
            
            <div class="col-lg-12 text-center" style="margin-bottom:30px; margin-top:30px">
                <a style="color:black; text-decoration:none" href="{% url "content:send_message" %}">
                    <div class="btn btn-default btn-lg see_all">Send A Message</div>
                </a>
            </div>
            
        </div>
            {% if page == "home" %}
            <div class="overlay" onClick="style.pointerEvents='none'"></div>
            <iframe src="https://mapsengine.google.com/map/u/0/embed?mid=zL7VsRnhknUc.kRzpVrHDJ4oo" width="100%" height="480" marginheight="0" marginwidth="0" frameborder="0" scrolling="no"></iframe>
            {% endif %}
            
        <div class="container text-center" style="margin-top:30px"> 
            <img src="{% static "img/logo.png" %}" height="150px">
            <p>Agri-Turf Supplies, Inc. Copyright &copy; {% now "Y" %}</p>
            <hr>

            <!-- Footer Links -->
            <p style="color:black; text-decoration:none">
                <a style="color:black; text-decoration:none" href="{% url "content:careers" %}">Careers</a> &nbsp;&nbsp; 
                <a style="color:black; text-decoration:none" href="{% url "content:terms_of_use" %}">Terms of Use</a> &nbsp;&nbsp; 
                <a style="color:black; text-decoration:none" href="/admin">Employee Portal</a>
            </p>
            <br>

        </div>
    </footer>

templates/_nav.html
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                {% if page == "home" %}
                <a class="navbar-brand page-scroll" href="#page-top">
                {% else %}
                <a class="navbar-brand page-scroll" href="/">
                {% endif %}
                    <span class="light">Agri-Turf</span> Solutions
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>

            {% if page == "home" %}

                <!-- Home page has a different nav bar -->
                <li>
                    <a class="page-scroll" href="#about"><i class="fa fa-users"></i><span class="verticalLine">&nbsp;</span>&nbsp;About</a>
                </li>
                <li>
                    <a href="{% url "services:search" %}" class=""><i class="fa fa-tree"></i><span class="verticalLine">&nbsp;</span>&nbsp;Solutions</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact"><i class="fa fa-globe"></i><span class="verticalLine">&nbsp;</span>&nbsp;Contact</a>
                </li>

            {% else %}

                <li>
                    <a class="{% if page == "about" %}active{% endif %}" href="{% url "content:about" %}"><i class="fa fa-users"></i><span class="verticalLine">&nbsp;</span>&nbsp;About</a>
                </li>
                <li>
                    <a href="{% url "services:search" %}" class="{% if page == "solutions" %}active{% endif %}"><i class="fa fa-tree"></i><span class="verticalLine">&nbsp;</span>&nbsp;Solutions</a>
                </li>
                <li>
                    <a class="{% if page == "contact" %}active{% endif %}" href="{% url "content:send_message" %}"><i class="fa fa-globe"></i><span class="verticalLine">&nbsp;</span>&nbsp;Contact</a>
                </li>

            {% endif %}
                <li>
                    <a class="{% if page == "cart" %}active{% endif %}" href="{% url "shop:cart" %}"><i class="fa fa-shopping-cart"></i><span class="verticalLine">&nbsp;</span>&nbsp;My Cart {% if request.session.cart_quantity %}({{ request.session.cart_quantity }}){% endif %}</a>
                </li>
            </ul>
            </div>
        </div>
    </nav>

    {% if request.session.cart_quantity %}
    <div class="checkout">
        <a href="{% url "shop:start_checkout" %}">
        <div style="background-color:rgba(153,0,0,1); border-color:rgba(153,0,0,1); color:white" class="btn btn-default">
            <h3 class="formobile" style="margin-bottom:0px">Checkout&nbsp;&nbsp;&nbsp;&nbsp;</h3>
        </div>
        </a>
    </div>
    {% endif %}

templates/base.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Agri-Turf Supplies">
    <link rel="icon" href="ico/favicon.ico">

    <!-- CSS -->
    {% block css %}
    <link href="{% static "css/bootstrap.css"%}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static "css/custom.css" %}" rel="stylesheet">
    <link href="{% static "css/cases.css" %}" rel="stylesheet">
    {% endblock %}

    <!-- Custom Fonts -->
    <link href="{% static 'fa-4.2.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <meta name="description" content="Family owned business for over 60 years providing affordable agricultural and pest/rodent control services and supplies in Santa Barbara county.">
    
    <title>{% block title %}Agri-Turf Supplies: {% block pagename %}Homepage{% endblock %}{% endblock %}</title>
    
</head>

<body{% block body_tag%}{%endblock%}>

<!-- Main Nav -->
{% include "_nav.html" with page=page %}
<!-- End Main Nav -->

<!-- Main Content -->
{% block content %}{% endblock %}
<!-- End Main Content -->

<!-- Footer -->
{% include "_footer.html" with page=page %}
<!-- End Footer -->

<!-- Javascript -->
    {% block javascript %}
    <!-- jQuery -->
    <script src="{% static "js/jquery.js" %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static "js/bootstrap.js" %}"></script>
    <!-- Plugin JavaScript -->
    <script src="{% static "js/jquery.easing.min.js" %}"></script>
    <!-- Custom Theme JavaScript -->
    <script src="{% static "js/grayscale.js" %}"></script>
    <!-- Form Validation -->
    <script src="{% static "js/validation.js" %}"></script>
    <!-- Google Analytics -->
    {% endblock %}
<!-- End Javascript -->
    
</body>

</html>